### PR TITLE
Added Resource Usage section.

### PR DESCRIPTION
**Pull request by irungentoo**
Read the commit.

### CODE REVIEW

**Comment by zetok** [comment]
This is stupid.

**Comment by stqism** [comment]
@zetok,

I'd have to agree in the sense that I feel like this is a ploy to attack qTox.

**Comment by GrayHatter** [comment]
Perhaps having hard size limits are the problem? Would percentages be better?

It's hard to argue with `The user must not think that he has to quit his tox client to run his other software more smoothly or to free up memory.` 

Tox is a Skype replacement, the reason that Skype is the standard is because it's so hard to close. No one is going to enforce quite the relationship that Skype has with the quit button, so the alternative is to make the user not WANT to close Tox.

**Comment by novist** [comment]
This kind of states the obvious - do not be a resource hog.

By the way for me qTox is idling at 89mb on windows and 74mb on linux while at the same time skype uses over 100mb with 3 contacts and two empty chat windows open and no fancy stuff like video calls.

Clients written in managed languages (c#/java) might have harder time complying but if they work good enough this part will surely be happily ignored by all - developers and users.

**Pull request merged**
