### PR TITLE
STS: Add an actual avatar section

### PR DESCRIPTION
**Pull request by zetok**
Summary:

"Ported" avatar section from:
https://github.com/irungentoo/Tox_Client_Guidelines/blob/master/Important/Avatars.md

* Adjusted format without change to content.
* Some fixes to typos/other

Arguments for:

* STS should describe how clients should handle avatars

Arguments against:

* It is not defined whether supporting avatars is a required feature to be
  considered to be a Tox client.
* This proposal encourages storing avatars in plain, unencrypted form, and
  does not take under consideration situation where client wants to encrypt
  all user data, including avatars.

Status quo:

Currently STS contains only a broken link to place where once content of
this proposal was located.

====
@dvor, @Impyy, @irungentoo, @tux3, @subliun

### CODE REVIEW

**Comment by Impyy** [comment]
Looks good to me!

**Comment by dvor** [comment]
> It is not defined whether supporting avatars is a required feature to be considered to be a Tox client.

I see two ways of improving this. We can choose on of them and add to STS:
- make avatars optional
- make avatars required for all GUI clients.

Personally I think that avatars should be nice to have, but optional feature. GUI Tox client without avatars will still have all messaging/calling capabilities and may be quite nice looking.

> This proposal encourages storing avatars in plain, unencrypted form, and does not take under consideration situation where client wants to encrypt all user data, including avatars.

This item can be left as it is for now and changed in future if needed.

**Comment by zetok** [comment]
>>It is not defined whether supporting avatars is a required feature to be considered to be a Tox client.

>I see two ways of improving this. We can choose on of them and add to STS:
>* make avatars optional
>* make avatars required for all GUI clients.
>
>Personally I think that avatars should be nice to have, but optional feature. GUI Tox client without avatars will still have all messaging/calling capabilities and may be quite nice looking.

Optional, but strongly suggested? ← does anyone have anything against this?

====

That being said, should this modification be done in this PR, or should this PR be (eventually) merged as is, and modification be done in another PR?

Furthermore, if change should be done in this PR, should new commit be squashed?

**Comment by tux3** [comment]
I agree with the current content of the PR.

>It is not defined whether supporting avatars is a required feature to be considered to be a Tox client.

For the sake of supporting a broad range of use cases (bots, text clients, ...) I don't think that avatars should be a requirement. A Tox client without avatars stills plays nice with other clients, so this should merely be optional.

>This proposal encourages storing avatars in plain, unencrypted form, and does not take under consideration situation where client wants to encrypt all user data, including avatars.

I'm happy with the status quo and with what this PR contains.

**Comment by subliun** [comment]
I think this is good for now. Could perhaps be improved later (change avatar size, add sts support for more formats), but it's good enough. Merge it.

**Comment by zetok** [comment]
@dvor since it's not quite clear what your stance is - is proposal in current form acceptable?

**Comment by dvor** [comment]
@zetok  yes, I agree

**Pull request merged**
