### PR TITLE
Fix DNS naming | 'tox#' → 'toxdns#'

### PR DESCRIPTION
**Pull request by zetok**
Summary:

Rename tox{1,2,3} to toxdns{1,2,3}

Arguments for:

It's good for you. Seriously. (read commit message)

Arguments against:

Redundancy.

Status quo:

Confuses users leading to damage to Tox's public Image, thus it should be changed.

I *hope* that you'll CC all people needed.

### CODE REVIEW

**Comment by dubslow** [comment]
I think the system written out in #47 is a system we should be using. @zetok Would you be willing to modify this PR to that system's standards?

**Comment by subliun** [comment]
I'm mostly okay with this. The only issue is that it changes the URI scheme which probably breaks something.

**Comment by zetok** [comment]
@subliun yes, it breaks.. literally everything. Those referenced PRs are (were?) supposed to ease transition, but breakage would still occur, and it will be a pain to deal with… The only thing I can say is that it's better to do it sooner…

**Comment by zetok** [comment]
Closing, since it doesn't look like it will get anywhere.

**Pull request closed without merging**
