### PR TITLE
STS: Mark avatar support as recommended, but not mandatory

### PR DESCRIPTION
**Pull request by zetok**
Summary:

According to @tux3 and @dvor's suggestion, support for avatars should be
recommended, but not mandatory for Tox clients.

Arguments for:

* Avatars should be be an optional feature, since clients can be visually
  appealing without them

Arguments against:

* GUI clients without support for avatars might be a bad surprise for people

Status quo:

Currently it is not specified whether clietns have to have avatar support.

====
@dvor, @Impyy, @irungentoo, @tux3, @subliun

### CODE REVIEW

**Comment by dvor** [comment]
Agree

**Comment by tux3** [comment]
According to me, I agree.

**Comment by Impyy** [comment]
I agree.

**Comment by GrayHatter** [comment]
no, I think avatar support needs to be required... Otherwise clients have to deal with non-compatible clients...

E.g. client A (STS) tries to send an avatar to client B (non-STS), starts the file transfer. Client B ignores it. Client A now has an outgoing file transfer that will never do anything taking up a FT slot, and possible the extra memory a client would have to devote to keeping an avatar ready to send.

Avatar support should be mandatory, but support could be as simple as rejecting any file transfer with kind == avatar...

**Comment by zetok** [comment]
So rather than optional full support, clients that don't want to display avatar should have **mandatory support for rejecting avatars**, + **optional support for receiving and displaying** them?

@dvor , @tux3 , @Impyy do you think that absolute no support for avatars is better than mandatory minimal support for rejecting them when client doesn't want to display / use them?

**Comment by Impyy** [comment]
@zetok Well no, clients should reject the transfer even if they don't support avatars. This should be clarified in the STS though.

**Comment by tux3** [comment]
I agree with @Impyy

**Comment by zetok** [comment]
Closing, since #64 got merged.

**Pull request closed without merging**
