### PR TITLE
Change 'friend' to 'contact'

### PR DESCRIPTION
**Pull request by Tirifto**
Changed all occurrences of the word 'friend' to the word 'contact', because it's more correct and neutral.

This pull request has already been discussed and accepted by voters, but due to an error in the commit description, it had to be updated. Original pull request can be seen here: #61

### CODE REVIEW

**Comment by zetok** [comment]
It should be added to ``arguments against`` that this change also makes it harder and more confusing to work with toxcore and developing a client, especially for people new to Tox.

**Comment by Tirifto** [comment]
@zetok 

Why? How? How does calling contacts 'contacts' make it harder to work with toxcore and developing a client?

**Comment by KoKuToru** [comment]
@Tirifto because toxcore calls it `friend`

**Comment by Tirifto** [comment]
@zetok @KoKuToru

Is it significant enough to be included as a drawback? I'm not a developer, so I can't judge that well.
(And I suppose I'll need to make yet another PR?)

Also, I suppose toxcore has a documentation that can be edited appropriately in case of need?

**Comment by zetok** [comment]
@Tirifto it's not about documentation that needs to be changed, but your changes simply making it harder and more confusing for anyone who would want to work with toxcore. Since clients has to use toxcore, you're making it harder for anyone who wants to do something with clients, that would adhere to STS.

**Comment by KoKuToru** [comment]
@Tirifto

can be hardly edited in toxcore, the public API uses "friend" like `tox_callback_friend_name` `tox_callback_friend_status_message`. Changing these would break the API.

Anyways that said .. I am 100% for contact :+1: 
But truth said, it might confuse new developers. 
We just need to write somewhere "we don't want to use `friend` as used in `toxcore` because ...."

**Pull request closed without merging**
