### PR TITLE
STS: Client should be responsible for taking care of message encoding

### PR DESCRIPTION
**Pull request by zetok**
Summary:

Changed responsibility for detecting and re-encoding invalid UTF-8 entered
by user.

Arguments for:

* Core acts only as a transport layer for messages
* Clients get messages, and should not rely on core to provide correct encoding

Arguments against:

* More effort for client developers?

Status quo:

Current STS may lead to belief that core takes care of encoding as UTF-8,
which is not the case.

====

Pls vote @dvor, @Impyy, @irungentoo, @tux3, @subliun

### CODE REVIEW

**Comment by KoKuToru** [comment]
It's not very clear that every string you get from toxcore should do this...

for tox_self_get_name, tox_friend_get_name_size, ... etc.

**Comment by zetok** [comment]
@KoKuToru Fair point. Do you think that changing ``message`` to ``text`` would be sufficient?

**Comment by subliun** [comment]
Both active developers of Antox support this change. 
Antox - yes

**Comment by Impyy** [comment]
Agreed, toxcore shouldn't and doesn't take care of this.

**Comment by dvor** [comment]
Agree on this, for every string from toxcore.

**Pull request merged**
