### PR TITLE
STS: Filename handling

### PR DESCRIPTION
**Pull request by KoKuToru**
**Summary:**

Description of how to handle filenames.

**Arguments for:**

These are arguments for the proposal:
* Makes sure files aren't hidden on unix-based systems (starting with `.`)
* Makes sure clients don't accidently write file somewhere else then the download folder
* Makes sure filenames are useable on a wide variety of filesystems

**Arguments against:**

These are arguments against the proposal:
* ugly filenames

**Status quo:**

Current behavior is client dependent.

### CODE REVIEW

**Comment by zetok** [comment]
why would you mess so much with filenames?

I.e. why should I have broken filenames just because some retarded OS doesn't support them?

**Comment by KoKuToru** [comment]
no idea, just wanted to share, there are problems with filenames.. 
and this is one possible ugly solution.

**Comment by zetok** [comment]
it would be better if special characters were dealt with on per-OS basis, e.g. for Linux that would exclude only ``/`` and ``\0``.

as for filenames starting with a dot on Linux - if someone sends a "hidden" file, IMHO it's up to them to explain why it's not visible anywhere..

**Comment by GrayHatter** [comment]
I agree with this PR, but I also agree with @zetok there's no reason to limit one OS because another decides some char's aren't safe...

We should add language that lists the unsafe chars for each OS, but then let the client handle it's own char set. That way developers get a warning before trusting filenames.

**Comment by zetok** [comment]
@KoKuToru could you please update your PR to suggested changes?

Or is there a good reason to not do so?

**Comment by KoKuToru** [comment]
sorry but I don't have time for this

**Pull request closed without merging**
