### PR TITLE
Separated firm Standards -> Proposed changes

### PR DESCRIPTION
**Pull request by GrayHatter**
Separated the firm Standards -> Proposed changes section

### CODE REVIEW

**Comment by zetok** [comment]
Except that encryption is not an option, but a requirement. Removing it as a requirement would leave users' secret keys without any protection, thus it has to be required from Tox client.

**Comment by GrayHatter** [comment]
@zetok read the commit changes, I meerly reworded that section and moved it.

My changes don't alter the meaning of the current text, only the phrasing. In it's current version STS says that it's optional.

Then I created and moved it in a 'new' pending changes section, because in the STS draft it says under discussion. Meaning that either way it's still NOT yet a requirement.

**Comment by GrayHatter** [comment]
Not to mention that if I have local access to the system you're already f'd

**Comment by zetok** [comment]
@GrayHatter uh, sorry,I should have read properly what is changed.

Let me disagree on being f'd if someone has access to system. #45

**Comment by stqism** [comment]
Please submit a formal issue requesting changes, how to here: https://github.com/Tox/Tox-STS/issues/47

**Pull request closed without merging**
